-- このモジュールは敵の図鑑データ定義を提供する。

local M = {}

-- 図鑑表示に限らず、出現判定・戦闘・UI表示で使う敵情報を定義する。
-- ステータスや出現条件もここに集約して管理する。
-- アイコンとキャラクターの一致感を最優先して構成する。
M.enemies = {
  {
    id = "dust_slime",
    name_en = "Lua Slime",
    name_ja = "ルアスライム",
    icon = "",
    stats = { hp = 4, atk = 1, def = 0, accuracy = 88 },
    elements = { "normal", "grass" },
    appear = { min = 1, max = 2 },
    flavor = {
      en = "A code-born slime that bubbles with gentle loops and sudden bursts.",
      ja = "穏やかなループと突発的な跳ねが混ざるコード生まれの粘体。",
    },
  },
  {
    id = "tux_penguin",
    name_en = "Tux Penguin",
    name_ja = "タックスペンギン",
    icon = "",
    stats = { hp = 5, atk = 2, def = 1, accuracy = 90 },
    elements = { "water", "light" },
    appear = { min = 1, max = 3 },
    flavor = {
      en = "A calm glider that answers the dungeon with crisp, icy steps.",
      ja = "涼やかな足取りでダンジョンに応える穏やかな滑走者。",
    },
  },
  {
    id = "vim_mantis",
    name_en = "Vim Mantis",
    name_ja = "ヴィムマンティス",
    icon = "",
    stats = { hp = 5, atk = 2, def = 1, accuracy = 91 },
    elements = { "grass", "light" },
    appear = { min = 1, max = 4 },
    flavor = {
      en = "It trims the corridor with razor focus, never wasting a keystroke.",
      ja = "鋭い集中で通路を刈り取り、無駄な一打を嫌う。",
    },
  },
  {
    id = "c_sentinel",
    name_en = "C Sentinel",
    name_ja = "Cセンチネル",
    icon = "",
    stats = { hp = 6, atk = 2, def = 1, accuracy = 90 },
    elements = { "normal", "fire" },
    appear = { min = 1, max = 4 },
    flavor = {
      en = "A simple guardian forged in raw steel, stubborn yet reliable.",
      ja = "原鋼で鍛えられた素朴な守り手。頑固だが頼れる。",
    },
  },
  {
    id = "cpp_colossus",
    name_en = "C++ Colossus",
    name_ja = "C++コロッサス",
    icon = "",
    stats = { hp = 6, atk = 3, def = 1, accuracy = 88 },
    elements = { "fire", "dark" },
    appear = { min = 2, max = 5 },
    flavor = {
      en = "Its layered armor reflects countless patterns of ancient craft.",
      ja = "幾重もの装甲に、古い技法の痕跡が刻まれている。",
    },
  },
  {
    id = "php_elephant",
    name_en = "PHP Elephant",
    name_ja = "PHPエレファント",
    icon = "",
    stats = { hp = 7, atk = 2, def = 2, accuracy = 86 },
    elements = { "grass", "normal" },
    appear = { min = 2, max = 5 },
    flavor = {
      en = "A towering guardian that never forgets a path through the jungle.",
      ja = "密林の道を忘れない巨体の守り手。",
    },
  },
  {
    id = "docker_whale",
    name_en = "Docker Whale",
    name_ja = "ドッカーホエール",
    icon = "",
    stats = { hp = 7, atk = 2, def = 2, accuracy = 85 },
    elements = { "water", "normal" },
    appear = { min = 2, max = 6 },
    flavor = {
      en = "It ferries entire ecosystems on its back and never loses buoyancy.",
      ja = "背に小さな世界を乗せ、浮力を失わない巨大な運び屋。",
    },
  },
  {
    id = "go_gopher",
    name_en = "Go Gopher",
    name_ja = "ゴーファー",
    icon = "",
    stats = { hp = 5, atk = 3, def = 1, accuracy = 90 },
    elements = { "fire", "normal" },
    appear = { min = 2, max = 6 },
    flavor = {
      en = "A cheerful sprinter that darts through corridors with blazing speed.",
      ja = "燃えるような速度で通路を駆け抜ける陽気な走り屋。",
    },
  },
  {
    id = "bash_hound",
    name_en = "Bash Hound",
    name_ja = "バッシュハウンド",
    icon = "",
    stats = { hp = 6, atk = 3, def = 1, accuracy = 90 },
    elements = { "normal", "dark" },
    appear = { min = 2, max = 6 },
    flavor = {
      en = "It obeys short commands and howls when paths become tangled.",
      ja = "短い命令に従い、道が絡まると遠吠えで警告する。",
    },
  },
  {
    id = "mysql_dolphin",
    name_en = "MySQL Dolphin",
    name_ja = "マイエスキューエルドルフィン",
    icon = "",
    stats = { hp = 6, atk = 3, def = 1, accuracy = 89 },
    elements = { "water", "light" },
    appear = { min = 3, max = 6 },
    flavor = {
      en = "It leaps through data streams, flicking droplets of polished light.",
      ja = "データの流れを跳ね、磨かれた光の雫を振り撒く。",
    },
  },
  {
    id = "postgres_colossus",
    name_en = "Postgres Colossus",
    name_ja = "ポストグレスコロッサス",
    icon = "",
    stats = { hp = 7, atk = 3, def = 2, accuracy = 87 },
    elements = { "water", "dark" },
    appear = { min = 3, max = 7 },
    flavor = {
      en = "An ancient titan that remembers every echo beneath the stone.",
      ja = "石の下の残響を覚えている古き巨像。",
    },
  },
  {
    id = "dbeaver",
    name_en = "DBeaver",
    name_ja = "ディービーバー",
    icon = "",
    stats = { hp = 6, atk = 3, def = 1, accuracy = 88 },
    elements = { "water", "grass" },
    appear = { min = 3, max = 6 },
    flavor = {
      en = "It chisels through data logs and builds dams of hardened queries.",
      ja = "データの流れを削り、固いクエリの堤を築く。",
    },
  },
  {
    id = "ruby_scarab",
    name_en = "Ruby Scarab",
    name_ja = "ルビースカラベ",
    icon = "",
    stats = { hp = 6, atk = 3, def = 1, accuracy = 89 },
    elements = { "light", "normal" },
    appear = { min = 3, max = 7 },
    flavor = {
      en = "Its crimson shell shimmers like a gem, warding off weaker blades.",
      ja = "宝石のように輝く紅い殻で、弱い刃を弾き返す。",
    },
  },
  {
    id = "clojure_oracle",
    name_en = "Clojure Oracle",
    name_ja = "クロージャオラクル",
    icon = "",
    stats = { hp = 5, atk = 4, def = 0, accuracy = 88 },
    elements = { "light", "dark" },
    appear = { min = 3, max = 7 },
    flavor = {
      en = "It mutters in circles, reshaping fate with every repeated phrase.",
      ja = "輪を描くように囁き、反復の言葉で運命を塗り替える。",
    },
  },
  {
    id = "node_phantom",
    name_en = "Node Phantom",
    name_ja = "ノードファントム",
    icon = "",
    stats = { hp = 5, atk = 4, def = 0, accuracy = 90 },
    elements = { "dark", "grass" },
    appear = { min = 3, max = 7 },
    flavor = {
      en = "It appears in pulses, vanishing between ticks of the event loop.",
      ja = "イベントループの隙間で揺らめき、脈動の合間に消える。",
    },
  },
  {
    id = "python_serpent",
    name_en = "Python Serpent",
    name_ja = "パイソンサーペント",
    icon = "",
    stats = { hp = 5, atk = 4, def = 0, accuracy = 87 },
    elements = { "grass", "dark" },
    appear = { min = 4, max = 8 },
    flavor = {
      en = "It coils around lanterns, squeezing until the light flickers.",
      ja = "灯りに絡みつき、光が揺らぐまで締め上げる。",
    },
  },
  {
    id = "java_ifrit",
    name_en = "Java Ifrit",
    name_ja = "ジャヴァイフリート",
    icon = "",
    stats = { hp = 6, atk = 4, def = 1, accuracy = 88 },
    elements = { "fire", "light" },
    appear = { min = 4, max = 8 },
    flavor = {
      en = "A fiery spirit that brews scorching steam with every roar.",
      ja = "咆哮のたびに灼熱の蒸気を沸き立たせる炎の精霊。",
    },
  },
  {
    id = "kotlin_fox",
    name_en = "Kotlin Fox",
    name_ja = "コトリンフォックス",
    icon = "",
    stats = { hp = 5, atk = 4, def = 1, accuracy = 90 },
    elements = { "light", "water" },
    appear = { min = 4, max = 8 },
    flavor = {
      en = "Its twin tails weave elegant paths, never stepping on the same stone twice.",
      ja = "双つの尾が優雅な軌跡を描き、同じ石を二度踏まない。",
    },
  },
  {
    id = "swift_raptor",
    name_en = "Swift Raptor",
    name_ja = "スウィフトラプター",
    icon = "",
    stats = { hp = 5, atk = 4, def = 1, accuracy = 90 },
    elements = { "light", "fire" },
    appear = { min = 4, max = 8 },
    flavor = {
      en = "A swift hunter that strikes before the echo of its steps arrives.",
      ja = "足音の反響が届く前に斬りかかる迅速な狩人。",
    },
  },
  {
    id = "git_wyrm",
    name_en = "Git Wyrm",
    name_ja = "ギットワーム",
    icon = "",
    stats = { hp = 7, atk = 4, def = 2, accuracy = 86 },
    elements = { "dark", "normal" },
    appear = { min = 4, max = 8 },
    flavor = {
      en = "It burrows through history, guarding every branch it touches.",
      ja = "履歴の地層を掘り進み、触れた枝を守り抜く。",
    },
  },
  {
    id = "rust_crab",
    name_en = "Rust Crab",
    name_ja = "ラストクラブ",
    icon = "",
    stats = { hp = 8, atk = 4, def = 2, accuracy = 84 },
    elements = { "fire", "dark" },
    appear = { min = 5, max = 8 },
    flavor = {
      en = "Its iron claws leave a warm glow and a lingering scent of metal.",
      ja = "鉄の鋏は温かな光を残し、金属の匂いを漂わせる。",
    },
  },
  {
    id = "gnu_bison",
    name_en = "GNU Bison",
    name_ja = "グヌーバイソン",
    icon = "",
    stats = { hp = 7, atk = 3, def = 2, accuracy = 87 },
    elements = { "normal", "dark" },
    appear = { min = 3, max = 7 },
    flavor = {
      en = "A sturdy bison that trudges forward, breaking walls with sheer will.",
      ja = "意志の力だけで壁を砕き、重い歩みで進む頑強なバイソン。",
    },
  },
  {
    id = "boss_ice_regent",
    name_en = "Ice Regent",
    name_ja = "氷王レジェント",
    icon = "",
    stats = { hp = 12, atk = 5, def = 3, accuracy = 92 },
    elements = { "water", "light" },
    appear = { stages = {} },
    flavor = {
      en = "A sovereign draped in frost, ruling the first halls with quiet authority.",
      ja = "霜を纏う主。静かな威厳で最初の回廊を統べる。",
    },
  },
  {
    id = "boss_docker_leviathan",
    name_en = "Docker Leviathan",
    name_ja = "ドッカーリヴァイアサン",
    icon = "",
    stats = { hp = 13, atk = 5, def = 3, accuracy = 90 },
    elements = { "water", "normal" },
    appear = { stages = {} },
    flavor = {
      en = "A colossal carrier that turns the corridor into a rolling tide.",
      ja = "回廊を奔流に変える、巨大な運び手。",
    },
  },
  {
    id = "boss_ruby_empress",
    name_en = "Ruby Empress",
    name_ja = "紅玉の女帝",
    icon = "",
    stats = { hp = 12, atk = 5, def = 3, accuracy = 91 },
    elements = { "light", "fire" },
    appear = { stages = {} },
    flavor = {
      en = "A jewel-bright ruler who commands the mid halls with radiant resolve.",
      ja = "宝石のように輝き、中層を照らして支配する女帝。",
    },
  },
  {
    id = "boss_python_prime",
    name_en = "Python Prime",
    name_ja = "パイソンプライム",
    icon = "",
    stats = { hp = 12, atk = 6, def = 2, accuracy = 91 },
    elements = { "grass", "dark" },
    appear = { stages = {} },
    flavor = {
      en = "An ancient coil that tightens every loop until the air cracks.",
      ja = "古の螺旋が輪を締め上げ、空気を裂くほど迫る。",
    },
  },
  {
    id = "boss_git_overlord",
    name_en = "Git Overlord",
    name_ja = "ギットオーバーロード",
    icon = "",
    stats = { hp = 13, atk = 6, def = 3, accuracy = 89 },
    elements = { "dark", "normal" },
    appear = { stages = {} },
    flavor = {
      en = "A tyrant of branching paths, sealing exits with layered history.",
      ja = "分岐の道を支配し、幾重の履歴で出口を封じる暴君。",
    },
  },
  {
    id = "boss_rust_juggernaut",
    name_en = "Rust Juggernaut",
    name_ja = "ラストジャガーノート",
    icon = "",
    stats = { hp = 14, atk = 6, def = 4, accuracy = 88 },
    elements = { "fire", "dark" },
    appear = { stages = {} },
    flavor = {
      en = "A relentless crusher whose armor heats the very stone around it.",
      ja = "装甲が石を灼くほどの熱を帯びた、止まらぬ破壊者。",
    },
  },
  {
    id = "boss_gnu_ancestral",
    name_en = "GNU Ancestral",
    name_ja = "グヌーの祖霊",
    icon = "",
    stats = { hp = 14, atk = 5, def = 4, accuracy = 90 },
    elements = { "normal", "dark" },
    appear = { stages = {} },
    flavor = {
      en = "An ancient guardian that tramples forward with unshakable creed.",
      ja = "揺るがぬ信条で踏み進む、古き守護者の祖霊。",
    },
  },
  {
    id = "boss_null_horizon",
    name_en = "Null Horizon",
    name_ja = "ヌルホライゾン",
    icon = "",
    stats = { hp = 15, atk = 7, def = 4, accuracy = 92 },
    elements = { "dark", "light" },
    appear = { stages = {} },
    flavor = {
      en = "A final boundary where light and shadow cancel, leaving only silence.",
      ja = "光と影が相殺され、沈黙だけが残る終端の境界。",
    },
  },
}

return M
