-- このモジュールは装備定義を提供する。

local util = require("idle_dungeon.util")

local M = {}

-- 解放条件は装備定義側で一元管理し、設定側と重複しないようにする。
-- 値は現在の進行速度に合わせて高めに設定する。
local unlock_rules = {
  typing_blade = { kind = "chars", value = 4000 },
  save_hammer = { kind = "saves", value = 200 },
  repeat_cloak = { kind = "time_sec", value = 36000 },
  edge_shield = { kind = "filetype_chars", filetype = "lua", value = 4000 },
  focus_bracelet = { kind = "chars", value = 12000 },
  lua_sigil_blade = { kind = "filetype_chars", filetype = "lua", value = 8000 },
  vim_focus_ring = { kind = "filetype_chars", filetype = "vim", value = 6000 },
  c_forge_spear = { kind = "filetype_chars", filetype = "c", value = 7000 },
  cpp_heap_shield = { kind = "filetype_chars", filetype = "cpp", value = 9000 },
  python_coil_whip = { kind = "filetype_chars", filetype = "python", value = 8000 },
  js_spark_blade = { kind = "filetype_chars", filetype = "javascript", value = 9000 },
  ts_guard_mail = { kind = "filetype_chars", filetype = "typescript", value = 9000 },
  go_stride_band = { kind = "filetype_chars", filetype = "go", value = 7000 },
  rust_crust_armor = { kind = "filetype_chars", filetype = "rust", value = 9000 },
  java_forge_staff = { kind = "filetype_chars", filetype = "java", value = 9000 },
  kotlin_arc_amulet = { kind = "filetype_chars", filetype = "kotlin", value = 8000 },
  swift_wind_dagger = { kind = "filetype_chars", filetype = "swift", value = 8000 },
  ruby_bloom_ring = { kind = "filetype_chars", filetype = "ruby", value = 8000 },
  php_bastion_cloak = { kind = "filetype_chars", filetype = "php", value = 8000 },
  bash_echo_charm = { kind = "filetype_chars", filetype = "sh", value = 6000 },
  shell_tide_ring = { kind = "filetype_chars", filetype = "bash", value = 6000 },
  html_canvas_cloak = { kind = "filetype_chars", filetype = "html", value = 6000 },
  css_palette_charm = { kind = "filetype_chars", filetype = "css", value = 6000 },
  json_mirror_ring = { kind = "filetype_chars", filetype = "json", value = 7000 },
  yaml_scroll_robe = { kind = "filetype_chars", filetype = "yaml", value = 7000 },
  toml_anchor_band = { kind = "filetype_chars", filetype = "toml", value = 7000 },
  sql_depth_spear = { kind = "filetype_chars", filetype = "sql", value = 8000 },
  markdown_quill_pendant = { kind = "filetype_chars", filetype = "markdown", value = 6000 },
}

-- 解放条件の定義を装備データへ反映して返す。
local function apply_unlock_rules(items, unlocks)
  local result = {}
  for _, item in ipairs(items or {}) do
    local unlock = unlocks[item.id]
    if unlock then
      table.insert(result, util.merge_tables(item, { unlock = unlock }))
    else
      table.insert(result, item)
    end
  end
  return result
end

-- 図鑑表示に使う英語名とフレーバーテキストも定義する。
-- 武器の属性タイプはelementで定義する。
-- rarityは戦利品の希少度を示し、common/rare/petを使う。
-- 敵コンテンツと雰囲気を揃えるため、フレーバー文は短く実戦感のあるトーンで統一する。
local base_items = {
  { id = "wood_sword", name = "木の剣", name_en = "Wooden Sword", slot = "weapon", atk = 2, element = "normal", price = 5, rarity = "common", flavor = { en = "Wooden Sword is a range-friendly weapon tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "木の剣はニュートラルレンジ向けに調整されたレンジ管理しやすいウェポン。クセが少なく、状況を選ばず使える。" } },
  { id = "round_shield", name = "丸盾", name_en = "Round Shield", slot = "weapon", def = 2, element = "normal", price = 6, rarity = "common", flavor = { en = "Round Shield is a maneuver-focused weapon tuned for neutral tempo. Its steady feel helps with small mid-fight recoveries.", ja = "丸盾はニュートラルレンジ向けに調整された取り回し重視のウェポン。安定感が高く、細かな立て直しに向く。" } },
  { id = "typing_blade", name = "タイピングブレード", name_en = "Typing Blade", slot = "weapon", atk = 7, element = "light", price = 70, rarity = "rare", flavor = { en = "Typing Blade is a maneuver-focused weapon tuned for light tempo. Mastering it can raise your whole combat pace by one step.", ja = "タイピングブレードはライトレンジ向けに調整された取り回し重視のウェポン。扱い切れば戦況を一段押し上げる。" } },
  { id = "save_hammer", name = "連続保存の槌", name_en = "Save Hammer", slot = "weapon", atk = 9, element = "dark", price = 90, rarity = "rare", flavor = { en = "Save Hammer is a maneuver-focused weapon tuned for shadow tempo. Mastering it can raise your whole combat pace by one step.", ja = "連続保存の槌はシャドウレンジ向けに調整された取り回し重視のウェポン。扱い切れば戦況を一段押し上げる。" } },
  { id = "short_spell_staff", name = "短い詠唱の杖", name_en = "Short Spell Staff", slot = "weapon", atk = 3, element = "fire", price = 25, rarity = "common", flavor = { en = "Short Spell Staff is a range-friendly weapon tuned for fire tempo. Low friction use makes it reliable in most situations.", ja = "短い詠唱の杖はファイアレンジ向けに調整されたレンジ管理しやすいウェポン。クセが少なく、状況を選ばず使える。" } },
  { id = "short_bow", name = "近距離弓", name_en = "Short Bow", slot = "weapon", atk = 2, element = "water", price = 12, rarity = "common", flavor = { en = "Short Bow is a maneuver-focused weapon tuned for water tempo. Its steady feel helps with small mid-fight recoveries.", ja = "近距離弓はウォーターレンジ向けに調整された取り回し重視のウェポン。安定感が高く、細かな立て直しに向く。" } },
  { id = "sand_staff", name = "砂の杖", name_en = "Sand Staff", slot = "weapon", atk = 2, def = 1, element = "normal", price = 14, rarity = "common", flavor = { en = "Sand Staff is a field-ready weapon tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "砂の杖はニュートラルレンジ向けに調整された実戦向けのウェポン。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "cloth_armor", name = "布の上着", name_en = "Cloth Armor", slot = "armor", def = 2, price = 5, rarity = "common", flavor = { en = "Cloth Armor is a impact-tolerant armor piece tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "布の上着はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。クセが少なく、状況を選ばず使える。" } },
  { id = "leather_armor", name = "革の上着", name_en = "Leather Armor", slot = "armor", def = 3, price = 10, rarity = "common", flavor = { en = "Leather Armor is a impact-tolerant armor piece tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "革の上着はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。クセが少なく、状況を選ばず使える。" } },
  { id = "thick_cloak", name = "厚手の外套", name_en = "Thick Cloak", slot = "armor", def = 3, hp = 1, price = 12, rarity = "common", flavor = { en = "Thick Cloak is a frontline armor piece tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "厚手の外套はニュートラルレンジ向けに調整された前線向けのアーマー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "light_robe", name = "薄手のローブ", name_en = "Light Robe", slot = "armor", def = 2, hp = 1, price = 8, rarity = "common", flavor = { en = "Light Robe is a line-holding armor piece tuned for neutral tempo. Its steady feel helps with small mid-fight recoveries.", ja = "薄手のローブはニュートラルレンジ向けに調整されたライン維持に向くアーマー。安定感が高く、細かな立て直しに向く。" } },
  { id = "repeat_cloak", name = "反復作業の外套", name_en = "Repeat Cloak", slot = "armor", def = 5, price = 60, rarity = "rare", flavor = { en = "Repeat Cloak is a frontline armor piece tuned for neutral tempo. Even at high output, it stays controllable into late battles.", ja = "反復作業の外套はニュートラルレンジ向けに調整された前線向けのアーマー。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "rest_armor", name = "小休止の鎧", name_en = "Rest Armor", slot = "armor", def = 6, hp = 2, price = 70, rarity = "rare", flavor = { en = "Rest Armor is a frontline armor piece tuned for neutral tempo. Even at high output, it stays controllable into late battles.", ja = "小休止の鎧はニュートラルレンジ向けに調整された前線向けのアーマー。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "edge_shield", name = "画面端の盾", name_en = "Edge Shield", slot = "armor", def = 4, hp = 2, price = 55, rarity = "rare", flavor = { en = "Edge Shield is a line-holding armor piece tuned for neutral tempo. Mastering it can raise your whole combat pace by one step.", ja = "画面端の盾はニュートラルレンジ向けに調整されたライン維持に向くアーマー。扱い切れば戦況を一段押し上げる。" } },
  { id = "record_ring", name = "記録の指輪", name_en = "Record Ring", slot = "accessory", hp = 2, price = 8, rarity = "common", flavor = { en = "Record Ring is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "記録の指輪はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "guard_amulet", name = "守りの護符", name_en = "Guard Amulet", slot = "accessory", def = 2, price = 10, rarity = "common", flavor = { en = "Guard Amulet is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "守りの護符はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "swift_ring", name = "疾風の指輪", name_en = "Swift Ring", slot = "accessory", atk = 2, price = 12, rarity = "common", flavor = { en = "Swift Ring is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "疾風の指輪はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "sleep_pendant", name = "安眠のペンダント", name_en = "Sleep Pendant", slot = "accessory", hp = 2, price = 9, rarity = "common", flavor = { en = "Sleep Pendant is a easy-carry accessory tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "安眠のペンダントはニュートラルレンジ向けに調整された携行しやすいアクセサリー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "fast_sand", name = "早送りの砂時計", name_en = "Fast-Forward Hourglass", slot = "accessory", hp = 2, atk = 2, price = 60, rarity = "rare", flavor = { en = "Fast-Forward Hourglass is a tempo-support accessory tuned for neutral tempo. Its scaling ceiling gives it strong presence against elites.", ja = "早送りの砂時計はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "silent_ear", name = "静音の耳飾り", name_en = "Silent Earring", slot = "accessory", hp = 1, def = 1, price = 15, rarity = "common", flavor = { en = "Silent Earring is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "静音の耳飾りはニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "focus_bracelet", name = "集中の腕輪", name_en = "Focus Bracelet", slot = "accessory", atk = 2, def = 2, price = 65, rarity = "rare", flavor = { en = "Focus Bracelet is a tempo-support accessory tuned for neutral tempo. Its scaling ceiling gives it strong presence against elites.", ja = "集中の腕輪はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  -- 属性ごとの装備バリエーションを追加して収集の幅を広げる。
  { id = "flame_dagger", name = "炎刃の短剣", name_en = "Flame Dagger", slot = "weapon", atk = 3, element = "fire", price = 14, rarity = "common", flavor = { en = "Flame Dagger is a range-friendly weapon tuned for fire tempo. Low friction use makes it reliable in most situations.", ja = "炎刃の短剣はファイアレンジ向けに調整されたレンジ管理しやすいウェポン。クセが少なく、状況を選ばず使える。" } },
  { id = "ember_bow", name = "熾火の弓", name_en = "Ember Bow", slot = "weapon", atk = 3, element = "fire", price = 16, rarity = "common", flavor = { en = "Ember Bow is a maneuver-focused weapon tuned for fire tempo. Its steady feel helps with small mid-fight recoveries.", ja = "熾火の弓はファイアレンジ向けに調整された取り回し重視のウェポン。安定感が高く、細かな立て直しに向く。" } },
  { id = "ash_mail", name = "灰の鎧", name_en = "Ash Mail", slot = "armor", def = 3, hp = 1, price = 14, rarity = "common", flavor = { en = "Ash Mail is a impact-tolerant armor piece tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "灰の鎧はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。クセが少なく、状況を選ばず使える。" } },
  { id = "cinder_band", name = "煤の腕輪", name_en = "Cinder Band", slot = "accessory", atk = 1, price = 12, rarity = "common", flavor = { en = "Cinder Band is a easy-carry accessory tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "煤の腕輪はニュートラルレンジ向けに調整された携行しやすいアクセサリー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "ember_charm", name = "熾火の護符", name_en = "Ember Charm", slot = "accessory", def = 1, price = 12, rarity = "common", flavor = { en = "Ember Charm is a easy-carry accessory tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "熾火の護符はニュートラルレンジ向けに調整された携行しやすいアクセサリー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "magma_greatsword", name = "溶岩の大剣", name_en = "Magma Greatsword", slot = "weapon", atk = 9, element = "fire", price = 85, rarity = "rare", flavor = { en = "Magma Greatsword is a maneuver-focused weapon tuned for fire tempo. Mastering it can raise your whole combat pace by one step.", ja = "溶岩の大剣はファイアレンジ向けに調整された取り回し重視のウェポン。扱い切れば戦況を一段押し上げる。" } },
  { id = "phoenix_cloak", name = "不死鳥の外套", name_en = "Phoenix Cloak", slot = "armor", def = 5, hp = 3, price = 75, rarity = "rare", flavor = { en = "Phoenix Cloak is a line-holding armor piece tuned for neutral tempo. Mastering it can raise your whole combat pace by one step.", ja = "不死鳥の外套はニュートラルレンジ向けに調整されたライン維持に向くアーマー。扱い切れば戦況を一段押し上げる。" } },
  { id = "tide_spear", name = "潮槍", name_en = "Tide Spear", slot = "weapon", atk = 3, element = "water", price = 14, rarity = "common", flavor = { en = "Tide Spear is a range-friendly weapon tuned for water tempo. Low friction use makes it reliable in most situations.", ja = "潮槍はウォーターレンジ向けに調整されたレンジ管理しやすいウェポン。クセが少なく、状況を選ばず使える。" } },
  { id = "mist_blade", name = "霧の刃", name_en = "Mist Blade", slot = "weapon", atk = 3, element = "water", price = 15, rarity = "common", flavor = { en = "Mist Blade is a maneuver-focused weapon tuned for water tempo. Its steady feel helps with small mid-fight recoveries.", ja = "霧の刃はウォーターレンジ向けに調整された取り回し重視のウェポン。安定感が高く、細かな立て直しに向く。" } },
  { id = "foam_coat", name = "泡の上着", name_en = "Foam Coat", slot = "armor", def = 3, hp = 1, price = 13, rarity = "common", flavor = { en = "Foam Coat is a impact-tolerant armor piece tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "泡の上着はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。クセが少なく、状況を選ばず使える。" } },
  { id = "ripple_charm", name = "波紋の護符", name_en = "Ripple Charm", slot = "accessory", def = 1, price = 11, rarity = "common", flavor = { en = "Ripple Charm is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "波紋の護符はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "tide_compass", name = "潮の羅針", name_en = "Tide Compass", slot = "accessory", atk = 1, price = 12, rarity = "common", flavor = { en = "Tide Compass is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "潮の羅針はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "abyss_trident", name = "深海の三叉槍", name_en = "Abyss Trident", slot = "weapon", atk = 9, element = "water", price = 85, rarity = "rare", flavor = { en = "Abyss Trident is a maneuver-focused weapon tuned for water tempo. Mastering it can raise your whole combat pace by one step.", ja = "深海の三叉槍はウォーターレンジ向けに調整された取り回し重視のウェポン。扱い切れば戦況を一段押し上げる。" } },
  { id = "leviathan_scale", name = "リヴァイアサンの鱗鎧", name_en = "Leviathan Scale", slot = "armor", def = 6, hp = 3, price = 80, rarity = "rare", flavor = { en = "Leviathan Scale is a line-holding armor piece tuned for neutral tempo. Mastering it can raise your whole combat pace by one step.", ja = "リヴァイアサンの鱗鎧はニュートラルレンジ向けに調整されたライン維持に向くアーマー。扱い切れば戦況を一段押し上げる。" } },
  { id = "moss_axe", name = "苔斧", name_en = "Moss Axe", slot = "weapon", atk = 3, element = "grass", price = 13, rarity = "common", flavor = { en = "Moss Axe is a range-friendly weapon tuned for green tempo. Low friction use makes it reliable in most situations.", ja = "苔斧はグリーンレンジ向けに調整されたレンジ管理しやすいウェポン。クセが少なく、状況を選ばず使える。" } },
  { id = "sprout_spear", name = "芽吹きの槍", name_en = "Sprout Spear", slot = "weapon", atk = 3, element = "grass", price = 14, rarity = "common", flavor = { en = "Sprout Spear is a maneuver-focused weapon tuned for green tempo. Its steady feel helps with small mid-fight recoveries.", ja = "芽吹きの槍はグリーンレンジ向けに調整された取り回し重視のウェポン。安定感が高く、細かな立て直しに向く。" } },
  { id = "vine_wrap", name = "蔦の外套", name_en = "Vine Wrap", slot = "armor", def = 3, hp = 1, price = 13, rarity = "common", flavor = { en = "Vine Wrap is a frontline armor piece tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "蔦の外套はニュートラルレンジ向けに調整された前線向けのアーマー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "leaf_locket", name = "木の葉のロケット", name_en = "Leaf Locket", slot = "accessory", hp = 1, price = 10, rarity = "common", flavor = { en = "Leaf Locket is a gap-cover accessory tuned for neutral tempo. Its steady feel helps with small mid-fight recoveries.", ja = "木の葉のロケットはニュートラルレンジ向けに調整された隙を埋めるアクセサリー。安定感が高く、細かな立て直しに向く。" } },
  { id = "pollen_charm", name = "花粉の護符", name_en = "Pollen Charm", slot = "accessory", def = 1, price = 11, rarity = "common", flavor = { en = "Pollen Charm is a gap-cover accessory tuned for neutral tempo. Its steady feel helps with small mid-fight recoveries.", ja = "花粉の護符はニュートラルレンジ向けに調整された隙を埋めるアクセサリー。安定感が高く、細かな立て直しに向く。" } },
  { id = "grove_reaver", name = "森影の大鎌", name_en = "Grove Reaver", slot = "weapon", atk = 9, element = "grass", price = 85, rarity = "rare", flavor = { en = "Grove Reaver is a field-ready weapon tuned for green tempo. Even at high output, it stays controllable into late battles.", ja = "森影の大鎌はグリーンレンジ向けに調整された実戦向けのウェポン。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "ancient_bark", name = "古樹の外殻", name_en = "Ancient Bark", slot = "armor", def = 6, hp = 3, price = 80, rarity = "rare", flavor = { en = "Ancient Bark is a impact-tolerant armor piece tuned for neutral tempo. Its scaling ceiling gives it strong presence against elites.", ja = "古樹の外殻はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "glimmer_rapier", name = "輝光のレイピア", name_en = "Glimmer Rapier", slot = "weapon", atk = 3, element = "light", price = 15, rarity = "common", flavor = { en = "Glimmer Rapier is a field-ready weapon tuned for light tempo. It is easy to handle and builds tempo from early fights.", ja = "輝光のレイピアはライトレンジ向けに調整された実戦向けのウェポン。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "halo_sling", name = "輪光のスリング", name_en = "Halo Sling", slot = "weapon", atk = 3, element = "light", price = 16, rarity = "common", flavor = { en = "Halo Sling is a field-ready weapon tuned for light tempo. It is easy to handle and builds tempo from early fights.", ja = "輪光のスリングはライトレンジ向けに調整された実戦向けのウェポン。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "radiant_veil", name = "光布のヴェール", name_en = "Radiant Veil", slot = "armor", def = 3, hp = 1, price = 14, rarity = "common", flavor = { en = "Radiant Veil is a frontline armor piece tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "光布のヴェールはニュートラルレンジ向けに調整された前線向けのアーマー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "prism_charm", name = "プリズムの護符", name_en = "Prism Charm", slot = "accessory", atk = 1, price = 12, rarity = "common", flavor = { en = "Prism Charm is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "プリズムの護符はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "beacon_ring", name = "導きの指輪", name_en = "Beacon Ring", slot = "accessory", hp = 1, price = 12, rarity = "common", flavor = { en = "Beacon Ring is a easy-carry accessory tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "導きの指輪はニュートラルレンジ向けに調整された携行しやすいアクセサリー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "dawn_blade", name = "黎明の剣", name_en = "Dawn Blade", slot = "weapon", atk = 9, element = "light", price = 90, rarity = "rare", flavor = { en = "Dawn Blade is a range-friendly weapon tuned for light tempo. Its scaling ceiling gives it strong presence against elites.", ja = "黎明の剣はライトレンジ向けに調整されたレンジ管理しやすいウェポン。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "aurora_plate", name = "極光の鎧", name_en = "Aurora Plate", slot = "armor", def = 6, hp = 3, price = 85, rarity = "rare", flavor = { en = "Aurora Plate is a impact-tolerant armor piece tuned for neutral tempo. Its scaling ceiling gives it strong presence against elites.", ja = "極光の鎧はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "dusk_katana", name = "黄昏の刀", name_en = "Dusk Katana", slot = "weapon", atk = 4, element = "dark", price = 17, rarity = "common", flavor = { en = "Dusk Katana is a range-friendly weapon tuned for shadow tempo. Low friction use makes it reliable in most situations.", ja = "黄昏の刀はシャドウレンジ向けに調整されたレンジ管理しやすいウェポン。クセが少なく、状況を選ばず使える。" } },
  { id = "shade_stiletto", name = "影のスティレット", name_en = "Shade Stiletto", slot = "weapon", atk = 3, element = "dark", price = 14, rarity = "common", flavor = { en = "Shade Stiletto is a maneuver-focused weapon tuned for shadow tempo. Its steady feel helps with small mid-fight recoveries.", ja = "影のスティレットはシャドウレンジ向けに調整された取り回し重視のウェポン。安定感が高く、細かな立て直しに向く。" } },
  { id = "umbra_mail", name = "陰の鎧", name_en = "Umbra Mail", slot = "armor", def = 3, hp = 1, price = 14, rarity = "common", flavor = { en = "Umbra Mail is a impact-tolerant armor piece tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "陰の鎧はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。クセが少なく、状況を選ばず使える。" } },
  { id = "void_ring", name = "虚無の指輪", name_en = "Void Ring", slot = "accessory", def = 1, price = 12, rarity = "common", flavor = { en = "Void Ring is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "虚無の指輪はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "gloom_pendant", name = "憂影のペンダント", name_en = "Gloom Pendant", slot = "accessory", atk = 1, price = 12, rarity = "common", flavor = { en = "Gloom Pendant is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "憂影のペンダントはニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "night_reaper", name = "夜刈りの大鎌", name_en = "Night Reaper", slot = "weapon", atk = 9, element = "dark", price = 90, rarity = "rare", flavor = { en = "Night Reaper is a maneuver-focused weapon tuned for shadow tempo. Mastering it can raise your whole combat pace by one step.", ja = "夜刈りの大鎌はシャドウレンジ向けに調整された取り回し重視のウェポン。扱い切れば戦況を一段押し上げる。" } },
  { id = "eclipse_cloak", name = "皆既の外套", name_en = "Eclipse Cloak", slot = "armor", def = 6, hp = 3, price = 85, rarity = "rare", flavor = { en = "Eclipse Cloak is a frontline armor piece tuned for neutral tempo. Even at high output, it stays controllable into late battles.", ja = "皆既の外套はニュートラルレンジ向けに調整された前線向けのアーマー。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "iron_lance", name = "鉄の槍", name_en = "Iron Lance", slot = "weapon", atk = 3, def = 1, element = "normal", price = 13, rarity = "common", flavor = { en = "Iron Lance is a range-friendly weapon tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "鉄の槍はニュートラルレンジ向けに調整されたレンジ管理しやすいウェポン。クセが少なく、状況を選ばず使える。" } },
  { id = "stone_maul", name = "石のメイス", name_en = "Stone Maul", slot = "weapon", atk = 4, element = "normal", price = 15, rarity = "common", flavor = { en = "Stone Maul is a maneuver-focused weapon tuned for neutral tempo. Its steady feel helps with small mid-fight recoveries.", ja = "石のメイスはニュートラルレンジ向けに調整された取り回し重視のウェポン。安定感が高く、細かな立て直しに向く。" } },
  { id = "traveler_coat", name = "旅人の上着", name_en = "Traveler Coat", slot = "armor", def = 3, hp = 1, price = 12, rarity = "common", flavor = { en = "Traveler Coat is a line-holding armor piece tuned for neutral tempo. Its steady feel helps with small mid-fight recoveries.", ja = "旅人の上着はニュートラルレンジ向けに調整されたライン維持に向くアーマー。安定感が高く、細かな立て直しに向く。" } },
  { id = "steady_band", name = "安定の腕輪", name_en = "Steady Band", slot = "accessory", hp = 1, def = 1, price = 12, rarity = "common", flavor = { en = "Steady Band is a easy-carry accessory tuned for neutral tempo. It is easy to handle and builds tempo from early fights.", ja = "安定の腕輪はニュートラルレンジ向けに調整された携行しやすいアクセサリー。扱いやすく、序盤からテンポを作りやすい。" } },
  { id = "traveler_token", name = "旅路の護符", name_en = "Traveler Token", slot = "accessory", def = 1, price = 11, rarity = "common", flavor = { en = "Traveler Token is a tempo-support accessory tuned for neutral tempo. Low friction use makes it reliable in most situations.", ja = "旅路の護符はニュートラルレンジ向けに調整されたテンポ補助に向くアクセサリー。クセが少なく、状況を選ばず使える。" } },
  { id = "guardian_halberd", name = "守護者の斧槍", name_en = "Guardian Halberd", slot = "weapon", atk = 7, def = 2, element = "normal", price = 80, rarity = "rare", flavor = { en = "Guardian Halberd is a field-ready weapon tuned for neutral tempo. Even at high output, it stays controllable into late battles.", ja = "守護者の斧槍はニュートラルレンジ向けに調整された実戦向けのウェポン。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "bulwark_plate", name = "城壁の鎧", name_en = "Bulwark Plate", slot = "armor", def = 7, hp = 3, price = 90, rarity = "rare", flavor = { en = "Bulwark Plate is a impact-tolerant armor piece tuned for neutral tempo. Its scaling ceiling gives it strong presence against elites.", ja = "城壁の鎧はニュートラルレンジ向けに調整された被弾を受け止めやすいアーマー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "lua_sigil_blade", name = "Luaの紋剣", name_en = "Lua Sigil Blade", slot = "weapon", atk = 7, element = "light", price = 95, rarity = "rare", flavor = { en = "Lua Sigil Blade is a range-friendly weapon tuned for light tempo. Its scaling ceiling gives it strong presence against elites.", ja = "Luaの紋剣はライトレンジ向けに調整されたレンジ管理しやすいウェポン。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "vim_focus_ring", name = "Vim集中指輪", name_en = "Vim Focus Ring", slot = "accessory", atk = 1, def = 2, element = "normal", price = 72, rarity = "rare", flavor = { en = "Vim Focus Ring is a gap-cover accessory tuned for neutral tempo. Mastering it can raise your whole combat pace by one step.", ja = "Vim集中指輪はニュートラルレンジ向けに調整された隙を埋めるアクセサリー。扱い切れば戦況を一段押し上げる。" } },
  { id = "c_forge_spear", name = "C鍛造の槍", name_en = "C Forge Spear", slot = "weapon", atk = 6, def = 1, element = "normal", price = 85, rarity = "rare", flavor = { en = "C Forge Spear is a field-ready weapon tuned for neutral tempo. Even at high output, it stays controllable into late battles.", ja = "C鍛造の槍はニュートラルレンジ向けに調整された実戦向けのウェポン。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "cpp_heap_shield", name = "C++ヒープ盾", name_en = "C++ Heap Shield", slot = "armor", def = 6, hp = 2, element = "dark", price = 90, rarity = "rare", flavor = { en = "C++ Heap Shield is a line-holding armor piece tuned for shadow tempo. Mastering it can raise your whole combat pace by one step.", ja = "C++ヒープ盾はシャドウレンジ向けに調整されたライン維持に向くアーマー。扱い切れば戦況を一段押し上げる。" } },
  { id = "python_coil_whip", name = "Python環鞭", name_en = "Python Coil Whip", slot = "weapon", atk = 6, element = "water", price = 88, rarity = "rare", flavor = { en = "Python Coil Whip is a range-friendly weapon tuned for water tempo. Its scaling ceiling gives it strong presence against elites.", ja = "Python環鞭はウォーターレンジ向けに調整されたレンジ管理しやすいウェポン。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "js_spark_blade", name = "JavaScript火花剣", name_en = "JavaScript Spark Blade", slot = "weapon", atk = 6, element = "fire", price = 86, rarity = "rare", flavor = { en = "JavaScript Spark Blade is a range-friendly weapon tuned for fire tempo. Its scaling ceiling gives it strong presence against elites.", ja = "JavaScript火花剣はファイアレンジ向けに調整されたレンジ管理しやすいウェポン。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "ts_guard_mail", name = "TypeScript守護の鎧", name_en = "TypeScript Guard Mail", slot = "armor", def = 5, hp = 2, element = "light", price = 88, rarity = "rare", flavor = { en = "TypeScript Guard Mail is a impact-tolerant armor piece tuned for light tempo. Its scaling ceiling gives it strong presence against elites.", ja = "TypeScript守護の鎧はライトレンジ向けに調整された被弾を受け止めやすいアーマー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "go_stride_band", name = "Goストライドバンド", name_en = "Go Stride Band", slot = "accessory", atk = 2, def = 1, element = "fire", price = 75, rarity = "rare", flavor = { en = "Go Stride Band is a gap-cover accessory tuned for fire tempo. Mastering it can raise your whole combat pace by one step.", ja = "Goストライドバンドはファイアレンジ向けに調整された隙を埋めるアクセサリー。扱い切れば戦況を一段押し上げる。" } },
  { id = "rust_crust_armor", name = "Rust外殻装甲", name_en = "Rust Crust Armor", slot = "armor", def = 6, hp = 2, element = "dark", price = 92, rarity = "rare", flavor = { en = "Rust Crust Armor is a impact-tolerant armor piece tuned for shadow tempo. Its scaling ceiling gives it strong presence against elites.", ja = "Rust外殻装甲はシャドウレンジ向けに調整された被弾を受け止めやすいアーマー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "java_forge_staff", name = "Java鍛錬の杖", name_en = "Java Forge Staff", slot = "weapon", atk = 7, element = "fire", price = 95, rarity = "rare", flavor = { en = "Java Forge Staff is a maneuver-focused weapon tuned for fire tempo. Mastering it can raise your whole combat pace by one step.", ja = "Java鍛錬の杖はファイアレンジ向けに調整された取り回し重視のウェポン。扱い切れば戦況を一段押し上げる。" } },
  { id = "kotlin_arc_amulet", name = "Kotlinアークアミュレット", name_en = "Kotlin Arc Amulet", slot = "accessory", atk = 1, def = 2, element = "light", price = 76, rarity = "rare", flavor = { en = "Kotlin Arc Amulet is a tempo-support accessory tuned for light tempo. Its scaling ceiling gives it strong presence against elites.", ja = "Kotlinアークアミュレットはライトレンジ向けに調整されたテンポ補助に向くアクセサリー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "swift_wind_dagger", name = "Swift風刃短剣", name_en = "Swift Wind Dagger", slot = "weapon", atk = 6, element = "water", price = 86, rarity = "rare", flavor = { en = "Swift Wind Dagger is a maneuver-focused weapon tuned for water tempo. Mastering it can raise your whole combat pace by one step.", ja = "Swift風刃短剣はウォーターレンジ向けに調整された取り回し重視のウェポン。扱い切れば戦況を一段押し上げる。" } },
  { id = "ruby_bloom_ring", name = "Ruby開花の指輪", name_en = "Ruby Bloom Ring", slot = "accessory", atk = 2, element = "grass", price = 78, rarity = "rare", flavor = { en = "Ruby Bloom Ring is a tempo-support accessory tuned for green tempo. Its scaling ceiling gives it strong presence against elites.", ja = "Ruby開花の指輪はグリーンレンジ向けに調整されたテンポ補助に向くアクセサリー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "php_bastion_cloak", name = "PHPバスティオン外套", name_en = "PHP Bastion Cloak", slot = "armor", def = 5, hp = 2, element = "grass", price = 86, rarity = "rare", flavor = { en = "PHP Bastion Cloak is a frontline armor piece tuned for green tempo. Even at high output, it stays controllable into late battles.", ja = "PHPバスティオン外套はグリーンレンジ向けに調整された前線向けのアーマー。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "bash_echo_charm", name = "Bash反響の護符", name_en = "Bash Echo Charm", slot = "accessory", def = 2, element = "dark", price = 72, rarity = "rare", flavor = { en = "Bash Echo Charm is a tempo-support accessory tuned for shadow tempo. Its scaling ceiling gives it strong presence against elites.", ja = "Bash反響の護符はシャドウレンジ向けに調整されたテンポ補助に向くアクセサリー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "shell_tide_ring", name = "Shell潮流の指輪", name_en = "Shell Tide Ring", slot = "accessory", hp = 2, element = "water", price = 72, rarity = "rare", flavor = { en = "Shell Tide Ring is a tempo-support accessory tuned for water tempo. Its scaling ceiling gives it strong presence against elites.", ja = "Shell潮流の指輪はウォーターレンジ向けに調整されたテンポ補助に向くアクセサリー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "html_canvas_cloak", name = "HTMLキャンバス外套", name_en = "HTML Canvas Cloak", slot = "armor", def = 4, hp = 2, element = "light", price = 82, rarity = "rare", flavor = { en = "HTML Canvas Cloak is a impact-tolerant armor piece tuned for light tempo. Its scaling ceiling gives it strong presence against elites.", ja = "HTMLキャンバス外套はライトレンジ向けに調整された被弾を受け止めやすいアーマー。伸びしろが大きく、強敵戦で存在感を出せる。" } },
  { id = "css_palette_charm", name = "CSSパレット護符", name_en = "CSS Palette Charm", slot = "accessory", atk = 1, def = 1, element = "light", price = 72, rarity = "rare", flavor = { en = "CSS Palette Charm is a easy-carry accessory tuned for light tempo. Even at high output, it stays controllable into late battles.", ja = "CSSパレット護符はライトレンジ向けに調整された携行しやすいアクセサリー。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "json_mirror_ring", name = "JSON鏡面指輪", name_en = "JSON Mirror Ring", slot = "accessory", def = 2, element = "water", price = 74, rarity = "rare", flavor = { en = "JSON Mirror Ring is a easy-carry accessory tuned for water tempo. Even at high output, it stays controllable into late battles.", ja = "JSON鏡面指輪はウォーターレンジ向けに調整された携行しやすいアクセサリー。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "yaml_scroll_robe", name = "YAML書巻ローブ", name_en = "YAML Scroll Robe", slot = "armor", def = 4, hp = 2, element = "grass", price = 84, rarity = "rare", flavor = { en = "YAML Scroll Robe is a line-holding armor piece tuned for green tempo. Mastering it can raise your whole combat pace by one step.", ja = "YAML書巻ローブはグリーンレンジ向けに調整されたライン維持に向くアーマー。扱い切れば戦況を一段押し上げる。" } },
  { id = "toml_anchor_band", name = "TOMLアンカーバンド", name_en = "TOML Anchor Band", slot = "accessory", hp = 1, def = 2, element = "normal", price = 74, rarity = "rare", flavor = { en = "TOML Anchor Band is a easy-carry accessory tuned for neutral tempo. Even at high output, it stays controllable into late battles.", ja = "TOMLアンカーバンドはニュートラルレンジ向けに調整された携行しやすいアクセサリー。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "sql_depth_spear", name = "SQL深層の槍", name_en = "SQL Depth Spear", slot = "weapon", atk = 7, element = "dark", price = 92, rarity = "rare", flavor = { en = "SQL Depth Spear is a field-ready weapon tuned for shadow tempo. Even at high output, it stays controllable into late battles.", ja = "SQL深層の槍はシャドウレンジ向けに調整された実戦向けのウェポン。高出力でも制御しやすく、終盤まで主力に残る。" } },
  { id = "markdown_quill_pendant", name = "Markdown羽根ペンダント", name_en = "Markdown Quill Pendant", slot = "accessory", atk = 1, hp = 1, element = "light", price = 70, rarity = "rare", flavor = { en = "Markdown Quill Pendant is a gap-cover accessory tuned for light tempo. Mastering it can raise your whole combat pace by one step.", ja = "Markdown羽根ペンダントはライトレンジ向けに調整された隙を埋めるアクセサリー。扱い切れば戦況を一段押し上げる。" } },
}

-- 解放条件を統合した装備定義を公開する。
M.items = apply_unlock_rules(base_items, unlock_rules)

return M
